# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttapp', '0004_auto_20170408_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='ctime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 8, 9, 40, 19, 733396)),
        ),
    ]
