# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttapp', '0007_auto_20170408_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crawler',
        ),
    ]
