# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttapp', '0009_crawler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
