# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttapp', '0010_auto_20170408_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='ctime',
            field=models.DateField(auto_now_add=True, verbose_name='create time'),
        ),
    ]
