# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttapp', '0012_auto_20170408_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='ctime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
