# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ttapp', '0015_auto_20170408_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='ctime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
